when@dev:
    _errors:
        resource: "@FrameworkBundle/Resources/config/routing/errors.xml"
        prefix: /_error

shop_route:
    path: /shop
    controller: App\Controller\ShopController::index